### ISSUE TITLE
Crash when no token is passed to streaming server

### ISSUE THREAD

**Issue by jeda** [crybapp/aperture#2]
For example, if you connect to http://<IP>:9000, it tries to parse the token, and if it's not given to it, it will completely crash, without even finishing the request. Simply browsing it causes this.

**Comment by lnneth** [comment]
Thats because there is no error handling in the event of that situation, you can submit a PR request adding that simple feature

**Comment by darnfish** [comment]
Fixed, see https://github.com/crybapp/aperture/commit/2ba2cb081d4494d0e205fbf0a852b23654b3e6ba. If you have any other issues then lmk! Closing for now.
