### ISSUE TITLE
Needs working with slow network situations and doing actual real-time streaming

### ISSUE THREAD

**Issue by jeda** [crybapp/aperture#3]
I've been looking into how aperture streams stuff - it needs some fixes and adding features on what is slow network handling, and what most surely will want - real-time streaming, and working around so it doesn't freezes every few due to slow networks.

By what I see - ffmpeg records all the stuff, then aperture just sends the data to the clients, as-is, and won't even do frame skipping etc. to prevent some issues. This would be an issue with those with slow networks and computers, so what's proposed is:

- [ ] Do multiple encodings of the stream, in SD and HD. Doesn't needs all of them be running at once, just depending if there's any client requesting for it, based on their situation.
- [ ] Check the performance of network and stream and switch automatically to the best choice.
- [ ] Do some skipping in case of high loss, instead of getting the whole stream which would desync stuff between viewers and cause some freezing in some cases.

Any ideas are welcome.

**Comment by JeDaYoshi** [comment]
The buffering would actually be something client-side, but I am adding it here just in case as it's related. Can open an issue in `@cryb/web` if wanted.

**Comment by jeda** [comment]
This has to do nowadays with #5, more with WebRTC in.

**Comment by jeda** [comment]
I'll close this in favour of #5.
